execute_process(
  COMMAND "sh" "${CMAKE_SOURCE_DIR}/Modules/describe.sh"
  WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
  OUTPUT_VARIABLE DESCRIBE
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(DESCRIBE STREQUAL "")
  set (VERSION_TAG "UNKNOWN")
else()
  string(REGEX REPLACE "^v" "" VERSION_TAG "${DESCRIBE}")
endif()

